owner: vintagesucks # Your GitHub username
repo: uptime # Your Github repository name

sites:
  - name: nikol.as
    url: https://nikol.as/
  - name: PPA (Ubuntu 22.04)
    url: https://vintagesucks.github.io/ppa/ubuntu/jammy/Packages

status-website:
  baseUrl: /uptime # where "repo" is your repository name
  name: Uptime
